"""Baseline migration

Revision ID: 90e30dab5b39
Revises: 
Create Date: 2024-02-29 23:39:25.101671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e30dab5b39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=255), nullable=True),
    sa.Column('salt', sa.VARCHAR(length=400), nullable=False),
    sa.Column('registration_date', sa.DATE(), nullable=False),
    sa.Column('last_login', sa.DATE(), nullable=False),
    sa.Column('email_notification', sa.BOOLEAN(), nullable=False),
    sa.Column('push_notification', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('ai_extracted_invoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_pdf', sa.VARCHAR(length=500), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=255), nullable=True),
    sa.Column('issue_date', sa.DATE(), nullable=True),
    sa.Column('sale_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=255), nullable=True),
    sa.Column('payment_deadline', sa.DATE(), nullable=True),
    sa.Column('added_date', sa.DATE(), nullable=False),
    sa.Column('is_issued', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_extraction_failure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_pdf', sa.VARCHAR(length=500), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_business_entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nip', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_business_entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nip', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_extracted_external_business_entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('extracted_invoice_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nip', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['extracted_invoice_id'], ['ai_extracted_invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_extracted_invoice_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('extracted_invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_description', sa.VARCHAR(), nullable=True),
    sa.Column('number_of_items', sa.INTEGER(), nullable=True),
    sa.Column('net_value', sa.FLOAT(), nullable=True),
    sa.Column('gross_value', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['extracted_invoice_id'], ['ai_extracted_invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_extracted_user_business_entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('extracted_invoice_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nip', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['extracted_invoice_id'], ['ai_extracted_invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_is_external_business_entity_recognized',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('extracted_invoice_id', sa.UUID(), nullable=False),
    sa.Column('external_business_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_recognized', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['external_business_entity_id'], ['external_business_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extracted_invoice_id'], ['ai_extracted_invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_is_user_business_entity_recognized',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('extracted_invoice_id', sa.UUID(), nullable=False),
    sa.Column('user_business_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_recognized', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_invoice_id'], ['ai_extracted_invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_business_entity_id'], ['user_business_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_business_entity_id', sa.UUID(), nullable=False),
    sa.Column('external_business_entity_id', sa.UUID(), nullable=False),
    sa.Column('invoice_pdf', sa.VARCHAR(length=500), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('issue_date', sa.DATE(), nullable=False),
    sa.Column('sale_date', sa.DATE(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=255), nullable=False),
    sa.Column('payment_deadline', sa.DATE(), nullable=False),
    sa.Column('added_date', sa.DATE(), nullable=False),
    sa.Column('is_settled', sa.BOOLEAN(), nullable=False),
    sa.Column('is_issued', sa.BOOLEAN(), nullable=False),
    sa.Column('in_trash', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['external_business_entity_id'], ['external_business_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_business_entity_id'], ['user_business_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_description', sa.VARCHAR(), nullable=False),
    sa.Column('number_of_items', sa.INTEGER(), nullable=False),
    sa.Column('net_value', sa.FLOAT(), nullable=False),
    sa.Column('gross_value', sa.FLOAT(), nullable=False),
    sa.Column('in_trash', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_item')
    op.drop_table('invoice')
    op.drop_table('ai_is_user_business_entity_recognized')
    op.drop_table('ai_is_external_business_entity_recognized')
    op.drop_table('ai_extracted_user_business_entity')
    op.drop_table('ai_extracted_invoice_item')
    op.drop_table('ai_extracted_external_business_entity')
    op.drop_table('user_business_entity')
    op.drop_table('external_business_entity')
    op.drop_table('ai_extraction_failure')
    op.drop_table('ai_extracted_invoice')
    op.drop_table('user')
    # ### end Alembic commands ###
