version: '3'

networks:
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  postgres-volume:

services:
######################FastAPI SERVICES - Beginning###########################

  main_api_service:
    container_name: main_api_service
    build: ./main_api_service
    image: ghcr.io/wojciechignasiak/main_api_service:0.0.1
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 8081:80
    expose:
      - 80
    networks:
      - backend-network
    restart: always
    volumes:
      - ./main_api_service:/usr/src/main_api_service/
    depends_on:
      - postgresql

######################FastAPI SERVICES - End###########################

######################Databases - Beginning###########################

  postgresql:
    container_name: postgresql
    image: postgres:16.0-alpine
    ports:
      - 5433:5432
    expose:
      - 5432
    networks:
      - backend-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"

######################Databases - End###########################